### ISSUE TITLE
key "Principled BSDF" not found'

### ISSUE THREAD

**Issue by zqc972** [armory3d/armory_templates#5]
I use blender 2.80 with ArmorySDK-2019-08 to open these templates in armory_templates-2019.08.zip, when i click "Play", it always prompts:key "Principled BSDF" not found',  error info like this(racetrack.blend):

Traceback (most recent call last):
  File "D:\ArmorySDK1908//armory/blender\arm\props_ui.py", line 523, in execute
    make.play()
  File "D:\ArmorySDK1908//armory/blender\arm\make.py", line 462, in play
    build(target=runtime_to_target(), is_play=True)
  File "D:\ArmorySDK1908//armory/blender\arm\make.py", line 346, in build
    export_data(fp, sdk_path)
  File "D:\ArmorySDK1908//armory/blender\arm\make.py", line 110, in export_data
    exporter.execute(bpy.context, asset_path, scene=scene)
  File "D:\ArmorySDK1908//armory/blender\arm\exporter.py", line 1970, in execute
    self.make_default_mat('armdefault', self.defaultMaterialObjects)
  File "D:\ArmorySDK1908//armory/blender\arm\exporter.py", line 1495, in make_default_mat
    mat.node_tree.nodes['Principled BSDF'].inputs[7].default_value = 0.25
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

location: <unknown location>:-1

is this problem a bug? please help me,thanks!

**Comment by luboslenco** [comment]
Hey, do you get the same problem when using the newer ArmorySDK-2019-09?
